version: '3.3'
services:
  webshopDB:
    image: mysql
    environment:
      MYSQL_DATABASE: 'myDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./init/init-script.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'